name: domainDrivenDesign
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Functionnal programming
  dartz: ^0.9.1
  # Immutable objects
  freezed_annotation: ^0.7.1
  # Implement Bloc pattern
  flutter_bloc: ^4.0.0
  # Connect Firebase apps
  firebase_core: ^0.4.5
  # Firebase authentication API
  firebase_auth: ^0.16.1
  # Database service
  cloud_firestore: ^0.13.6
  # Access google signin
  google_sign_in: ^4.5.1
  # Service locator
  get_it: ^4.0.2
  # Code generator for get it => generate singleton & factories for us auto
  injectable: ^0.4.0+1
  # Create snackbars
  flushbar: ^1.10.4
  # Generate unique IDs
  uuid: ^2.0.4
  # Manage routing
  auto_route: ^0.5.0
  # Immutable Lists
  kt_dart: ^0.7.0+1
  # Used with freezed
  json_annotation: ^3.0.1

dev_dependencies:
  # Build system for Dart code generation and modular compilation
  build_runner:
  # Code generation for immutable classes
  freezed: ^0.10.9
  # Lint rules for Dart and Flutter to get a cleaner code
  lint: ^1.1.1
  # Code generator for get_it
  injectable_generator: ^0.4.0
  auto_route_generator: ^0.5.0
  # Used with freezed
  json_serializable: ^3.3.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
